apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: .
      image: nginx-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**

