apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-auto
  template:
    metadata:
      labels:
        app: nginx-auto
    spec:
      containers:
      - name: server
        image: nginx-auto
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
